// <auto-generated />
using System;
using GoallyticsApp.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoallyticsApp.Persistance.Migrations
{
    [DbContext(typeof(MatchContext))]
    [Migration("20250923152301_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Definition = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Definition = "Member"
                        });
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.AppUserRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppRoleId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppRoleId");

                    b.HasIndex("AppUserId", "AppRoleId")
                        .IsUnique();

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Definition = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Definition = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Definition = "Prefer not to say"
                        });
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.FixtureStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Ball_Possession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Blocked_Shots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Corner_Kicks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<string>("Fouls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goalkeeper_Saves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueApiId")
                        .HasColumnType("int");

                    b.Property<string>("Offsides")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passes_Percent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passes_accurate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Red_Cards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonApiId")
                        .HasColumnType("int");

                    b.Property<string>("Shots_insidebox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shots_off_Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shots_on_Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shots_outsidebox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total_Shots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total_passes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yellow_Cards")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId", "HomeTeamId");

                    b.HasIndex("FixtureId", "TeamId")
                        .IsUnique();

                    b.ToTable("FixtureStat");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Fixtures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("FixturesId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueApiId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("RoundApiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeasonApiId")
                        .HasColumnType("int");

                    b.Property<string>("StatusShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueApiId");

                    b.HasIndex("RoundApiId");

                    b.HasIndex("SeasonApiId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Leagues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeagueApiId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueApiId")
                        .HasColumnType("int");

                    b.Property<string>("RoundApiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeasonApiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueApiId");

                    b.HasIndex("SeasonApiId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeasonApiId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Founded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("National")
                        .HasColumnType("bit");

                    b.Property<int>("TeamApiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.AppUser", b =>
                {
                    b.HasOne("GoallyticsApp.Domain.Entities.AuthEntities.Gender", "Gender")
                        .WithMany("AppUsers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.AppUserRoles", b =>
                {
                    b.HasOne("GoallyticsApp.Domain.Entities.AuthEntities.AppRole", "AppRole")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoallyticsApp.Domain.Entities.AuthEntities.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.FixtureStat", b =>
                {
                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Fixtures", "Fixtures")
                        .WithMany("FStats")
                        .HasForeignKey("FixtureId", "HomeTeamId")
                        .HasPrincipalKey("FixturesId", "HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Fixtures", b =>
                {
                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Team", "AwayTeam")
                        .WithMany("AwayFixtures")
                        .HasForeignKey("AwayTeamId")
                        .HasPrincipalKey("TeamApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Team", "HomeTeam")
                        .WithMany("HomeFixtures")
                        .HasForeignKey("HomeTeamId")
                        .HasPrincipalKey("TeamApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Leagues", "League")
                        .WithMany("Fixtures")
                        .HasForeignKey("LeagueApiId")
                        .HasPrincipalKey("LeagueApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Round", "Round")
                        .WithMany("Fixtures")
                        .HasForeignKey("RoundApiId")
                        .HasPrincipalKey("RoundApiId");

                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Season", "Season")
                        .WithMany("Fixtures")
                        .HasForeignKey("SeasonApiId")
                        .HasPrincipalKey("SeasonApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Round");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Round", b =>
                {
                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Leagues", "League")
                        .WithMany("Rounds")
                        .HasForeignKey("LeagueApiId")
                        .HasPrincipalKey("LeagueApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoallyticsApp.Domain.Entities.MatchEntities.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonApiId")
                        .HasPrincipalKey("SeasonApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.AppRole", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.AppUser", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.AuthEntities.Gender", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Fixtures", b =>
                {
                    b.Navigation("FStats");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Leagues", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Round", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Season", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("GoallyticsApp.Domain.Entities.MatchEntities.Team", b =>
                {
                    b.Navigation("AwayFixtures");

                    b.Navigation("HomeFixtures");
                });
#pragma warning restore 612, 618
        }
    }
}
